# .github/workflows/deploy.yml
name: ğŸš€ Deploy to Fly.io

on: push

jobs:
  deploy:
    name: ğŸ›« Deploy FastAPI app
    runs-on: ubuntu-latest
    concurrency: deploy-group # Ensure only one action runs at a time
    steps:
      - name: ğŸ“¦ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ¦ Fly High with Fly.io
        uses: superfly/flyctl-actions@1.5
        with:
          args: deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
